// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi38qTWMwqe5FEL2Fh3eE8FV_a_80ZL20',
    appId: '1:425899366128:web:f97836c2828f5af885d435',
    messagingSenderId: '425899366128',
    projectId: 'hufstory-studyapp',
    authDomain: 'hufstory-studyapp.firebaseapp.com',
    storageBucket: 'hufstory-studyapp.appspot.com',
    measurementId: 'G-1H1K04ZJ0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39gD3LB9o85IDi05SOuCo5Ef9kdvJMgM',
    appId: '1:425899366128:android:c3d9b4ba32b7eb9e85d435',
    messagingSenderId: '425899366128',
    projectId: 'hufstory-studyapp',
    storageBucket: 'hufstory-studyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPHl2lQF9QuqHGBJrXkxWM1jZm_tfBkfM',
    appId: '1:425899366128:ios:4ff949f55f7818fc85d435',
    messagingSenderId: '425899366128',
    projectId: 'hufstory-studyapp',
    storageBucket: 'hufstory-studyapp.appspot.com',
    iosClientId: '425899366128-19honj225ejlk0v79kr2ia2a572dt409.apps.googleusercontent.com',
    iosBundleId: 'com.example.login1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPHl2lQF9QuqHGBJrXkxWM1jZm_tfBkfM',
    appId: '1:425899366128:ios:4ff949f55f7818fc85d435',
    messagingSenderId: '425899366128',
    projectId: 'hufstory-studyapp',
    storageBucket: 'hufstory-studyapp.appspot.com',
    iosClientId: '425899366128-19honj225ejlk0v79kr2ia2a572dt409.apps.googleusercontent.com',
    iosBundleId: 'com.example.login1',
  );
}
